[target."cfg(all())"]
runner = "sudo -E"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "linker=aarch64-linux-musl-gcc"]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = ["-C", "linker=x86_64-linux-musl-gcc"]

[env]
CC_aarch64_unknown_linux_musl = "aarch64-linux-musl-gcc"
CC_x86_64_unknown_linux_musl = "x86_64-linux-musl-gcc"
